[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
  { id = "detect-private-key" },
  { id = "check-added-large-files" },
]

[[repos]]
repo = "local"
hooks = [
  { id = "oxfmt", name = "oxfmt", entry = "npm exec -- oxfmt", language = "system", types_or = [
    "javascript",
    "ts",
    "json",
    "markdown",
  ] },
  { id = "oxlint", name = "oxlint", entry = "npm exec -- oxlint", language = "system", types_or = [
    "javascript",
    "ts",
  ] },
]
